name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v11
      with:
        name: tmp-ogdr2mkf7
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build
